Tidied option processing

diff --git a/toVibe b/toVibe
--- a/toVibe
+++ b/toVibe
@@ -3,7 +3,7 @@
 # toVibe [ -or ] dir ... - copy MP3s in dir to
 #                          /run/media/$LOGNAME/vibe/Music/dir
 #
-# Sun Oct 19 19:47:55 BST 2014
+# Mon Jan 12 12:40:02 GMT 2015
 #
 
 <<'______________D__O__C__U__M__E__N__T__A__T__I__O__N_____________'
@@ -160,9 +160,9 @@ vibeFull(){
 
   { printf "$NAME: (Vibe full?) "
     case $reason in
-         4)   echo "\`$vibeDest': can't create directory" ;;
-         5)   echo "\`$item': couldn't copy" ;;
-         *)   echo "\`$reason': unknown reason" ;;
+      4) echo "\`$vibeDest': can't create directory" ;;
+      5) echo "\`$item': couldn't copy" ;;
+      *) echo "\`$reason': unknown reason" ;;
     esac
   } >&2
   exit 4
@@ -277,11 +277,11 @@ fi
 #
 while getopts ':hor' option
 do   case $option in
-          h )   usage ;;
-          o )   overwrite=yes ;;
-          r )   removeSources=yes ;;
-         '?')   echo "$NAME: unknown option: \`$OPTARG'" >&2
-                usage ;;
+       h) usage ;;
+       o) overwrite=yes ;;
+       r) removeSources=yes ;;
+      \?) echo "$NAME: unknown option: \`$OPTARG'" >&2
+          usage
      esac
 done
 shift $(($OPTIND - 1))
