Fixed error code bug

diff --git a/toVibe b/toVibe
--- a/toVibe
+++ b/toVibe
@@ -105,14 +105,18 @@ usage(){
 }
 
 
-# mkTmp - make temp dir and delete it automatically on exit
+# mkTmp - make temp dir and delete it automatically on exit or failure
 #         Eg: mkTmp; ... > $TMP/temp
 #
 mkTmp(){
   TMP=/tmp/$NAME.$$
-  trap 'rm -fr $TMP 2> /dev/null; exit' 0 1 2 3 4 5 6 7 8 9 10    12 13 14 15
+
+  # Beware of exit from a subshell and losing exit code
+  #
+  trap 'code=$?; rm -fr $TMP 2> /dev/null; exit $code' \
+                                   HUP INT QUIT ILL ABRT BUS FPE SEGV PIPE TERM
   mkdir $TMP && return
-  echo " $NAME: couldn't make $TMP directory"  >&2
+  echo "$NAME: couldn't make \`$TMP' directory" >&2
   exit 2
 }
 
